-- Eliminar tablas en orden inverso a su creación (primero las más dependientes)
DROP TABLE ACTIVACIONES_MENSUALES;
DROP TABLE ASISTENCIAS;
DROP TABLE MANTENIMIENTOS;
DROP TABLE EVALUACIONES_FISICAS;
DROP TABLE PRODUCTOS_VENDIDOS;
DROP TABLE PRODUCTOS_SURTIDOS;
DROP TABLE CONTRATOS;
DROP TABLE PAGOS_MEMBRESIA;
DROP TABLE VENTAS;
DROP TABLE PEDIDOS;
DROP TABLE IMPLEMENTOS;
DROP TABLE PLANES_ENTRENAMIENTO;
DROP TABLE TECNICOS;
DROP TABLE ENTRENADORES;
DROP TABLE RECEPCIONISTAS;
DROP TABLE PRODUCTOS;
DROP TABLE PROVEEDORES;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;



-- Crear tabla CLIENTES
CREATE TABLE CLIENTES (
    idCliente VARCHAR2(10 CHAR) NOT NULL,
    nombreCliente VARCHAR2(30 CHAR),
    telefonoCliente VARCHAR2(10 CHAR),
    correoCliente VARCHAR2(30 CHAR),
    sexoCliente VARCHAR2(9 CHAR)
);

ALTER TABLE CLIENTES
    ADD CONSTRAINT CLIENTE_PK PRIMARY KEY (idCliente);

-- Crear tabla PROVEEDORES
CREATE TABLE PROVEEDORES (
    idProveedor VARCHAR2(10 CHAR) NOT NULL,
    condicionesDePago VARCHAR2(30 CHAR),
    telefonoProveedor VARCHAR2(30 CHAR),
    correoProveedor VARCHAR2(30 CHAR)
);

ALTER TABLE PROVEEDORES
    ADD CONSTRAINT PROVEEDOR_PK PRIMARY KEY (idProveedor);

-- Crear tabla PRODUCTOS
CREATE TABLE PRODUCTOS (
    idProducto VARCHAR2(10) NOT NULL,
    precioProducto NUMBER(2),
    nombreProducto VARCHAR2(20 CHAR),
    stock INTEGER,
    marcaProducto VARCHAR2(10),
    descripcionProducto VARCHAR2(10)
);

ALTER TABLE PRODUCTOS
    ADD CONSTRAINT PRODUCTO_PK PRIMARY KEY (idProducto);

-- Crear tabla RECEPCIONISTAS
CREATE TABLE RECEPCIONISTAS (
    idRecepcionista VARCHAR2(10 CHAR) NOT NULL,
    nombreRecepcionista VARCHAR2(30 CHAR),
    horarioTrabajo DATE,
    salario NUMBER(2)
);

ALTER TABLE RECEPCIONISTAS
    ADD CONSTRAINT RECEPCIONISTA_PK PRIMARY KEY (idRecepcionista);
    
-- Crear tabla ENTRENADORES
CREATE TABLE ENTRENADORES (
    idEntrenador VARCHAR2(10 CHAR) NOT NULL,
    nombreEntrenador VARCHAR2(30 CHAR),
    reputacion INTEGER,
    costoHora NUMBER
);

ALTER TABLE ENTRENADORES
    ADD CONSTRAINT ENTRENADOR_PK PRIMARY KEY (idEntrenador);

-- Crear tabla TECNICOS
CREATE TABLE TECNICOS (
    idTecnico VARCHAR2(10 CHAR) NOT NULL,
    nombreTecnico VARCHAR2(10 CHAR),
    costoHora NUMBER,
    tituloAcademico BLOB,
    telefonoTecnico VARCHAR2(10 CHAR)
);

ALTER TABLE TECNICOS
    ADD CONSTRAINT TECNICO_PK PRIMARY KEY (idTecnico);
    
-- Crear tabla PLANES_ENTRENAMIENTO
CREATE TABLE PLANES_ENTRENAMIENTO (
    idPlan VARCHAR2(10 CHAR) NOT NULL,
    objetivoPlan VARCHAR2(100 CHAR),
    duracionPlan DATE,
    costoPlan NUMBER(2),
    observaciones VARCHAR2(100 CHAR)
);

ALTER TABLE PLANES_ENTRENAMIENTO
    ADD CONSTRAINT PLAN_ENTRENAMIENTO_PK PRIMARY KEY (idPlan);
    
-- Crear tabla IMPLEMENTOS
CREATE TABLE IMPLEMENTOS (
    idImplemento VARCHAR2(10 CHAR) NOT NULL,
    nombreImplemento VARCHAR2(20),
    inicioServicio DATE,
    finServicio DATE
);

ALTER TABLE IMPLEMENTOS
    ADD CONSTRAINT IMPLEMENTO_PK PRIMARY KEY (idImplemento);
    
-- Crear tabla PEDIDOS
CREATE TABLE PEDIDOS (
    idPedido VARCHAR2(10 CHAR) NOT NULL,
    fechaDePetición DATE,
    estadoPedido VARCHAR2(10 CHAR),
    fechaEntrega DATE,
    idProveedor VARCHAR2(10 CHAR)
);

ALTER TABLE PEDIDOS
    ADD CONSTRAINT PEDIDO_PK PRIMARY KEY (idPedido);

ALTER TABLE PEDIDOS
    ADD CONSTRAINT PEDIDO_PROVEEDOR_FK FOREIGN KEY (idProveedor)
        REFERENCES PROVEEDORES (idProveedor);
        
-- Crear tabla VENTAS
CREATE TABLE VENTAS (
    idVenta VARCHAR2(10 CHAR) NOT NULL,
    fechaVenta VARCHAR2(10 CHAR),
    idCliente VARCHAR2(10 CHAR),
    idRecepcionista VARCHAR2(10 CHAR)
);

ALTER TABLE VENTAS
    ADD CONSTRAINT VENTA_PK PRIMARY KEY (idVenta);

ALTER TABLE VENTAS
    ADD CONSTRAINT VENTA_CLIENTE_FK FOREIGN KEY (idCliente)
        REFERENCES CLIENTES (idCliente);

ALTER TABLE VENTAS
    ADD CONSTRAINT VENTA_RECEPCIONISTA_FK FOREIGN KEY (idRecepcionista)
        REFERENCES RECEPCIONISTAS (idRecepcionista);
        
-- Crear tabla PAGOS_MEMBRESIA
CREATE TABLE PAGOS_MEMBRESIA (
    idPago VARCHAR2(10 CHAR) NOT NULL,
    fechaPago DATE,
    valorPago NUMBER(2),
    estadoPago VARCHAR2(10 CHAR),
    metodoPago VARCHAR2(10 CHAR)
);

ALTER TABLE PAGOS_MEMBRESIA
    ADD CONSTRAINT PAGO_MEMBRESIA_PK PRIMARY KEY (idPago);
    
-- Crear tabla CONTRATOS
CREATE TABLE CONTRATOS (
    idContrato VARCHAR2(10) NOT NULL,
    fechaInicio DATE,
    fechaCierre DATE,
    idCliente VARCHAR2(10 CHAR),
    idPlan VARCHAR2(10 CHAR)
);

ALTER TABLE CONTRATOS
    ADD CONSTRAINT CONTRATO_PK PRIMARY KEY (idContrato);

ALTER TABLE CONTRATOS
    ADD CONSTRAINT CONTRATO_CLIENTE_FK FOREIGN KEY (idCliente)
        REFERENCES CLIENTES (idCliente);

ALTER TABLE CONTRATOS
    ADD CONSTRAINT CONTRATO_PLAN_ENTRENAMIENTO_FK FOREIGN KEY (idPlan)
        REFERENCES PLANES_ENTRENAMIENTO (idPlan);
        
-- Crear tabla PRODUCTOS_SURTIDOS
CREATE TABLE PRODUCTOS_SURTIDOS (
    idSurtidos VARCHAR2(10) NOT NULL,
    cantidadProducto INTEGER,
    idProducto VARCHAR2(10),
    idPedido VARCHAR2(10 CHAR)
);

ALTER TABLE PRODUCTOS_SURTIDOS
    ADD CONSTRAINT PRODUCTO_SURTIDO_PK PRIMARY KEY (idSurtidos);

ALTER TABLE PRODUCTOS_SURTIDOS
    ADD CONSTRAINT PRODUCTO_SURTIDO_PRODUCTO_FK FOREIGN KEY (idProducto)
        REFERENCES PRODUCTOS (idProducto);

ALTER TABLE PRODUCTOS_SURTIDOS
    ADD CONSTRAINT PRODUCTO_SURTIDO_PEDIDO_FK FOREIGN KEY (idPedido)
        REFERENCES PEDIDOS (idPedido);

-- Crear tabla PRODUCTOS_VENDIDOS
CREATE TABLE PRODUCTOS_VENDIDOS (
    idVendidos VARCHAR2(10) NOT NULL,
    idVenta VARCHAR2(10 CHAR),
    cantidadTotal INTEGER,
    idProducto VARCHAR2(10)
);

ALTER TABLE PRODUCTOS_VENDIDOS
    ADD CONSTRAINT PRODUCTO_VENDIDO_PK PRIMARY KEY (idVendidos);

ALTER TABLE PRODUCTOS_VENDIDOS
    ADD CONSTRAINT PRODUCTO_VENDIDO_VENTA_FK FOREIGN KEY (idVenta)
        REFERENCES VENTAS (idVenta);

ALTER TABLE PRODUCTOS_VENDIDOS
    ADD CONSTRAINT PRODUCTO_VENDIDO_PRODUCTO_FK FOREIGN KEY (idProducto)
        REFERENCES PRODUCTOS (idProducto);
        
-- Crear tabla EVALUACIONES_FISICAS
CREATE TABLE EVALUACIONES_FISICAS (
    idEvaluación VARCHAR2(10 CHAR) NOT NULL,
    fechaEvaluacion DATE,
    peso FLOAT(2),
    estatura NUMBER(2),
    IMC FLOAT(2),
    porcentajeGrasa FLOAT(2),
    observaciones VARCHAR2(100),
    idCliente VARCHAR2(10 CHAR),
    idEntrenador VARCHAR2(10 CHAR)
);

ALTER TABLE EVALUACIONES_FISICAS
    ADD CONSTRAINT EVALUACION_FISICA_PK PRIMARY KEY (idEvaluación);

ALTER TABLE EVALUACIONES_FISICAS
    ADD CONSTRAINT EVALUACION_FISICA_CLIENTE_FK FOREIGN KEY (idCliente)
        REFERENCES CLIENTES (idCliente);

ALTER TABLE EVALUACIONES_FISICAS
    ADD CONSTRAINT EVALUACION_FISICA_ENTRENADOR_FK FOREIGN KEY (idEntrenador)
        REFERENCES ENTRENADORES (idEntrenador);

-- Crear tabla MANTENIMIENTOS
CREATE TABLE MANTENIMIENTOS (
    idMantenimiento VARCHAR2(10 CHAR) NOT NULL,
    fechaMantenimiento DATE,
    observacionesMantenimiento VARCHAR2(100 CHAR),
    idImplemento VARCHAR2(10 CHAR),
    idTecnico VARCHAR2(10 CHAR)
);

ALTER TABLE MANTENIMIENTOS
    ADD CONSTRAINT MANTENIMIENTO_PK PRIMARY KEY (idMantenimiento);

ALTER TABLE MANTENIMIENTOS
    ADD CONSTRAINT MANTENIMIENTO_IMPLEMENTO_FK FOREIGN KEY (idImplemento)
        REFERENCES IMPLEMENTOS (idImplemento);

ALTER TABLE MANTENIMIENTOS
    ADD CONSTRAINT MANTENIMIENTO_TECNICO_FK FOREIGN KEY (idTecnico)
        REFERENCES TECNICOS (idTecnico);

-- Crear tabla ASISTENCIAS
CREATE TABLE ASISTENCIAS (
    idAsistencia VARCHAR2(10 CHAR) NOT NULL,
    fechaAsistencia DATE,
    horaLlegada DATE,
    horaSalida DATE,
    idCliente VARCHAR2(10 CHAR)
);

ALTER TABLE ASISTENCIAS
    ADD CONSTRAINT ASISTENCIA_PK PRIMARY KEY (idAsistencia);

ALTER TABLE ASISTENCIAS
    ADD CONSTRAINT ASISTENCIA_CLIENTE_FK FOREIGN KEY (idCliente)
        REFERENCES CLIENTES (idCliente);
    
-- Crear tabla ACTIVACIONES_MENSUALES
CREATE TABLE ACTIVACIONES_MENSUALES (
    idActivacion VARCHAR2(10 CHAR) NOT NULL,
    idContrato VARCHAR2(10),
    idPago VARCHAR2(10 CHAR)
);

ALTER TABLE ACTIVACIONES_MENSUALES
    ADD CONSTRAINT ACTIVACION_MENSUAL_PK PRIMARY KEY (idActivacion);

ALTER TABLE ACTIVACIONES_MENSUALES
    ADD CONSTRAINT ACTIVACION_MENSUAL_CONTRATO_FK FOREIGN KEY (idContrato)
        REFERENCES CONTRATOS (idContrato);

ALTER TABLE ACTIVACIONES_MENSUALES
    ADD CONSTRAINT ACTIVACION_MENSUAL_PAGO_MEMBRESIA_FK FOREIGN KEY (idPago)
        REFERENCES PAGOS_MEMBRESIA (idPago);

